

from typing import List

from pdf_loader import PageInfo

class XpdfPythonCapsule: ...

def construct(filename: str) -> XpdfPythonCapsule: ...
    
def extractText(capsule: XpdfPythonCapsule) -> List[bytes]: ...

def extractImages(capsule: XpdfPythonCapsule) -> List[PageInfo]: ...

def deleteObject(capsule: XpdfPythonCapsule) -> None: ...
